# Generated by Django 5.2.4 on 2025-07-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/chat_default.jpg', null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
